version: "3.8"

services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/task
      - /var/task/.git
      - /var/task/node_modules
      - /var/task/.cache
      - ./tmp:/tmp
    ports:
      - 9000:8080
    environment:
      - LOCAL=true

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts:/etc/localstack/init/ready.d"
