FROM public.ecr.aws/lambda/nodejs:18

RUN yum install -y amazon-linux-extras
RUN amazon-linux-extras install -y epel
RUN yum install -y \
  at-spi2-atk cups-libs libdrm libxkbcommon libXcomposite libXdamage libXrandr mesa-libgbm pango alsa-lib\
  ipa-gothic-fonts ipa-mincho-fonts

WORKDIR ${LAMBDA_TASK_ROOT}
COPY package*.json .puppeteerrc.cjs ./
RUN npm install

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "index.handler" ]